A_Email/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'emails'

urlpatterns = [
    path('', views.list_emails, name="list_emails"),
    path('<int:email_id>/', views.read_mail, name="read_mail"),
]

B_User/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('configuration/', views.list_config, name="list_config"),
    path('login_user/', views.login_user, name="login_user"),
    
]

CRM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('email/', include('A_Email.urls')),
    path('user/', include('B_User.urls')),
    path('notes/', include('D_Notes.urls')),
    path('clients/', include('C_Client.urls')),
    path('users/', include('django.contrib.auth.urls'))

]

C_Client/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'client'

urlpatterns = [
    path('add_client/', views.add_client, name="add_client"),
    path('read_clients/', views.read_clients, name="read_clients"),
    path('update_client/<int:client_id>', views.update_client, name='update_client'),
    path('<int:client_id>/', views.delete_client, name="delete_client"),
]

D_Notes/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    path('add_note/', views.add_note, name="add_note"),
    path('read_note/', views.read_notes, name='read_note'),
    path('update_note/<int:note_id>', views.update_note, name='update_note'),
    path('delete_note/<int:note_id>', views.delete_note, name='delete_note'),

]

templates/add_client.html
{% extends 'main.html'%}

{% block content %}

   <div class="form-wrapper">
    <h1 class="table-header">Add Client:</h1>
            <form class="form_centered" action="" method=POST>
                {%csrf_token%}

                {% for field in form %}
                <div class="form-field">
                    <label class="form-label">{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="div-button">
                    <button type="submit" class="table-button">{% if client is None %}Add{% else %}Update{% endif%}</button>  
                </div>
            
            </form>
    </div>

    
    
{% endblock %}

templates/add_note.html
{% extends 'main.html'%}

{% block content %}

   <div class="form-wrapper form-note">
    <h1 class="table-header">Add Note:</h1>
            <form action="" method=POST>
                {%csrf_token%}

                {% for field in form %}
                <div class="form-field">
                    <label class="form-label">{{ field.label_tag }}</label>
                
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="div-button">
                <button type="submit" value="Add" class="table-button">{% if note is None %}Add{% else %}Update{% endif%}</button>
                </div>
            </form>
    </div>

    
    
{% endblock %}

templates/configuration.html
{% extends 'main.html'%}

{% block content %}

   <div class="form-wrapper">
    <h1 class="table-header">E-Mail Configuration:</h1>
         
            <form class="form_centered" action="" method=POST>
                {%csrf_token%}

                {% for field in form %}
                <div class="form-field">
                    <label class="form-label">{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="div-button">
                <button type="submit" class="table-button">{% if config is None %}Submit{% else %}Update{% endif%}</button>
                </div>
            </form>
    </div>

    
    
{% endblock %}

templates/email.html
{% extends 'main.html'%}

{% block content %}
<div class="table-wrapper">
<h1 class="table-header">E-Mails</h1>
<table class="table">
    <tr class="table-row">
        <th>Client</th>
        <th>Date</th>
        <th>Subject</th>
        <th>Read</th>
        <th>Action</th>
    </tr>
    {% for email in read_emails %}
    <tr class="table-row">
        <td>{% if email.clt is None %}{{email.sender}}{% else %}{{email.clt.name}} {{email.clt.surname}}{% endif%}</td>
        <td>{{email.dateReceived}}</td>
        <td> <a href="{% url 'emails:read_mail' email.id%}"> {{email.subject}}</a></td>
        <td>{{email.read}}</td>
        <td><button class="table-button table-button-delete">Delete</button></td>
    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}

templates/email_detail.html
{% extends 'main.html'%}

{% block content %}
<div class="form-wrapper email-width">
<h1 class="table-header">Email Detail</h1>

<div class="email-wrapper">
<div>
    <label class="inline-block" for="date">Date: </label>
    <p class="inline-block">{{email.dateReceived}}</p>
</div>

<div>
    <label class="inline-block" for="sender">Sender:</label>
    <p class="inline-block">{{email.sender}}</p>
</div>

<div>
    <label class="inline-block" for="to">To: </label>
    <p class="inline-block">{{email.to}}</p>
</div>

<div>
    <label class="inline-block" for="subject">Subject: </label>
    <p class="inline-block">{{email.subject}}</p>
</div>
<div>
    <label class="inline-block" for="message">Message: </label>
    <p class="inline-block">{{email.message}}</p>
</div>
</div>

<div class="email-button-wrapper">
    <button class="table-button">Reply</button>
    <button class="table-button table-button-delete">Delete</button>
</div>
</div>

{% endblock %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Familjen+Grotesk:wght@500&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/21cef00367.js" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    
    <div  class="navbar">
    {% include 'navbar.html'%}
    </div>
    <div class="topbar"></div>
    <div class="bottomcontent">
        {% block content%}
        {% endblock%}
    </div>
    


</body>
</html>

templates/navbar.html
<ul class="navbar">
    <h1 class="grid-row-span-2">
        CRM
    </h1>
    <li class="grid-align-vertical">
        <i class="fa fa-envelope" aria-hidden="true"></i>
        <a class="navbar-anchor" href="{% url 'emails:list_emails'%}">Inbox</a>
    </li>
    <li class="grid-align-vertical dropdown">
        <i class="fa-solid fa-list"></i>
        <a class="navbar-anchor" href="{% url 'notes:read_note'%}">To-Do-List</a>
        <i class="fa-solid fa-caret-down"></i>
        <div class="dropdown-content">
            <a class="navbar-anchor" href="{% url 'notes:add_note'%}">- Add Notes</a>
        </div>
    </li>
    <li class="grid-align-vertical dropdown">
        <i class="fa-solid fa-user"></i>
        <a class="navbar-anchor" href="{% url 'client:read_clients'%}">Clients</a>
        <i class="fa-solid fa-caret-down"></i>
        <div class="dropdown-content">
            <a class="navbar-anchor" href="{% url 'client:add_client'%}">- Add Clients</a>
        </div>
    </li>

    <li class="grid-align-vertical">
        <i class="fa-regular fa-address-card"></i>
        <a class="navbar-anchor" href="#services">Recent Contacts</a>
    </li>
    <li class="grid-align-vertical">
        <i class="fa-solid fa-envelope-open-text"></i>
        <a class="navbar-anchor" href="#services">Bulk E-Mails</a>
    </li>
    <li class="grid-align-vertical">
        <i class="fa-solid fa-signature"></i>
        <a class="navbar-anchor" href="#services">Signatures</a>
    </li>
    <li class="grid-align-vertical">
        <i class="fa-solid fa-gear"></i>
        <a class="navbar-anchor" href="{% url 'user:list_config'%}">Configuration</a>
    </li>
</ul>


   

templates/read_clients.html
{% extends 'main.html'%}

{% block content %}

   <div class="table-wrapper">
    <h1 class="table-header">Clients</h1>
    <table class="table">
        <tr class="table-row">
            
            <th>Name</th>
            <th>Surname</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
        {% for client in all_clients %}
        <tr class="table-row">   
            <td>{{ client.name }}</td>
            <td>{{ client.surname }}</td>
            <td>{{ client.eml }}</td>
            <td><button class="table-button"><a class="table-anchor" href="{% url 'client:update_client' client.id %}">Edit</a></button>
                <button class="table-button table-button-delete"><a class="table-anchor" href="{% url 'client:delete_client' client.id %}">Delete</a></button></td>
        </tr>
        {% endfor %}

    </table>
</div>
    
{% endblock %}

templates/testing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Familjen+Grotesk:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="bg-primary col-2">
                test
            </div>
            <div class="bg-primary col-2">
                test
            </div>
        </div>
    </div>
</body>

templates/to_dos.html
{% extends 'main.html'%}

{% block content %}

   <div class="table-wrapper">
    <h1 class="table-header">To Do List:</h1>
    <table class="table">
        <tr class="table-row">
            
            <th>Created</th>
            <th>Client</th>
            <th>Deadline</th>
            <th>Contact Type</th>
            <th>Title</th>
            <th>Summary</th>
            <th>Action</th>
        </tr>
        {% for todo in todo_notes %}
        <tr class="table-row">   
            <td>{{ todo.createDate }}</td>
            <td>{{ todo.client }}</td>
            <td><input type="date" value="{{ todo.deadline|date:'Y-m-d' }}"></td>
            <td>{{ todo.contact_type }}</td>
            <td>{{ todo.title }}</td>
            <td>{{ todo.summary }}</td>
            <td><button class="table-button"><a class="table-anchor" href="{% url 'notes:update_note' todo.id %}">Edit</a></button><button class="table-button table-button-delete"><a class="table-anchor" href="{% url 'notes:delete_note' todo.id %}">Delete</a></button></td>
        </tr>
        {% endfor %}

    </table>
</div>
{% endblock %}